from typing import Final, Literal

from tortoise import fields
from tortoise.models import Model


class File(Model):
    """
    Model for file record
    """

    slug = fields.CharField(10, pk=True, unique=True, null=False)
    data = fields.BinaryField(null=False)
    created_at = fields.DatetimeField(auto_now_add=True, null=False)
    downloads = fields.IntField()
    last_edited = fields.DatetimeField(auto_now=True)
    expires_at = fields.DatetimeField(null=True)

    class Meta:
        table = "files"


ALL_MIME_TYPES: Final = {
    "js": "text/javascript",
    "mjs": "text/javascript",
    "json": "application/json",
    "webmanifest": "application/manifest+json",
    "doc": "application/msword",
    "dot": "application/msword",
    "wiz": "application/msword",
    "nq": "application/n-quads",
    "nt": "application/n-triples",
    "bin": "application/octet-stream",
    "other": "application/octet-stream",
    "a": "application/octet-stream",
    "dll": "application/octet-stream",
    "exe": "application/octet-stream",
    "o": "application/octet-stream",
    "obj": "application/octet-stream",
    "so": "application/octet-stream",
    "oda": "application/oda",
    "pdf": "application/pdf",
    "p7c": "application/pkcs7-mime",
    "ps": "application/postscript",
    "ai": "application/postscript",
    "eps": "application/postscript",
    "trig": "application/trig",
    "m3u": "application/vnd.apple.mpegurl",
    "m3u8": "application/vnd.apple.mpegurl",
    "xls": "application/vnd.ms-excel",
    "xlb": "application/vnd.ms-excel",
    "ppt": "application/vnd.ms-powerpoint",
    "pot": "application/vnd.ms-powerpoint",
    "ppa": "application/vnd.ms-powerpoint",
    "pps": "application/vnd.ms-powerpoint",
    "pwz": "application/vnd.ms-powerpoint",
    "wasm": "application/wasm",
    "bcpio": "application/x-bcpio",
    "cpio": "application/x-cpio",
    "csh": "application/x-csh",
    "dvi": "application/x-dvi",
    "gtar": "application/x-gtar",
    "hdf": "application/x-hdf",
    "h5": "application/x-hdf5",
    "latex": "application/x-latex",
    "mif": "application/x-mif",
    "cdf": "application/x-netcdf",
    "nc": "application/x-netcdf",
    "p12": "application/x-pkcs12",
    "pfx": "application/x-pkcs12",
    "ram": "application/x-pn-realaudio",
    "pyc": "application/x-python-code",
    "pyo": "application/x-python-code",
    "sh": "application/x-sh",
    "shar": "application/x-shar",
    "swf": "application/x-shockwave-flash",
    "sv4cpio": "application/x-sv4cpio",
    "sv4crc": "application/x-sv4crc",
    "tar": "application/x-tar",
    "tcl": "application/x-tcl",
    "tex": "application/x-tex",
    "texi": "application/x-texinfo",
    "texinfo": "application/x-texinfo",
    "roff": "application/x-troff",
    "t": "application/x-troff",
    "tr": "application/x-troff",
    "man": "application/x-troff-man",
    "me": "application/x-troff-me",
    "ms": "application/x-troff-ms",
    "ustar": "application/x-ustar",
    "src": "application/x-wais-source",
    "xsl": "application/xml",
    "rdf": "application/xml",
    "wsdl": "application/xml",
    "xpdl": "application/xml",
    "zip": "application/zip",
    "3gp": "audio/3gpp",
    "3gpp": "audio/3gpp",
    "3g2": "audio/3gpp2",
    "3gpp2": "audio/3gpp2",
    "aac": "audio/aac",
    "adts": "audio/aac",
    "loas": "audio/aac",
    "ass": "audio/aac",
    "au": "audio/basic",
    "snd": "audio/basic",
    "mp3": "audio/mpeg",
    "mp2": "audio/mpeg",
    "opus": "audio/opus",
    "aif": "audio/x-aiff",
    "aifc": "audio/x-aiff",
    "aiff": "audio/x-aiff",
    "ra": "audio/x-pn-realaudio",
    "wav": "audio/x-wav",
    "avif": "image/avif",
    "bmp": "image/bmp",
    "gif": "image/gif",
    "ief": "image/ief",
    "jpg": "image/jpeg",
    "jpe": "image/jpeg",
    "jpeg": "image/jpeg",
    "heic": "image/heic",
    "heif": "image/heif",
    "png": "image/png",
    "svg": "image/svg+xml",
    "tiff": "image/tiff",
    "tif": "image/tiff",
    "ico": "image/vnd.microsoft.icon",
    "ras": "image/x-cmu-raster",
    "pnm": "image/x-portable-anymap",
    "pbm": "image/x-portable-bitmap",
    "pgm": "image/x-portable-graymap",
    "ppm": "image/x-portable-pixmap",
    "rgb": "image/x-rgb",
    "xbm": "image/x-xbitmap",
    "xpm": "image/x-xpixmap",
    "xwd": "image/x-xwindowdump",
    "eml": "message/rfc822",
    "mht": "message/rfc822",
    "mhtml": "message/rfc822",
    "nws": "message/rfc822",
    "css": "text/css",
    "csv": "text/csv",
    "html": "text/html",
    "htm": "text/html",
    "n3": "text/n3",
    "txt": "text/plain",
    "bat": "text/plain",
    "c": "text/plain",
    "h": "text/plain",
    "ksh": "text/plain",
    "pl": "text/plain",
    "srt": "text/plain",
    "rtx": "text/richtext",
    "tsv": "text/tab-separated-values",
    "vtt": "text/vtt",
    "py": "text/x-python",
    "etx": "text/x-setext",
    "sgm": "text/x-sgml",
    "sgml": "text/x-sgml",
    "vcf": "text/x-vcard",
    "xml": "text/xml",
    "mp4": "video/mp4",
    "mpeg": "video/mpeg",
    "m1v": "video/mpeg",
    "mpa": "video/mpeg",
    "mpe": "video/mpeg",
    "mpg": "video/mpeg",
    "mov": "video/quicktime",
    "qt": "video/quicktime",
    "webm": "video/webm",
    "avi": "video/x-msvideo",
    "movie": "video/x-sgi-movie",
}

MIME_TYPE = Literal[
    "js",
    "mjs",
    "json",
    "webmanifest",
    "doc",
    "dot",
    "wiz",
    "nq",
    "nt",
    "bin",
    "other",
    "a",
    "dll",
    "exe",
    "o",
    "obj",
    "so",
    "oda",
    "pdf",
    "p7c",
    "ps",
    "ai",
    "eps",
    "trig",
    "m3u",
    "m3u8",
    "xls",
    "xlb",
    "ppt",
    "pot",
    "ppa",
    "pps",
    "pwz",
    "wasm",
    "bcpio",
    "cpio",
    "csh",
    "dvi",
    "gtar",
    "hdf",
    "h5",
    "latex",
    "mif",
    "cdf",
    "nc",
    "p12",
    "pfx",
    "ram",
    "pyc",
    "pyo",
    "sh",
    "shar",
    "swf",
    "sv4cpio",
    "sv4crc",
    "tar",
    "tcl",
    "tex",
    "texi",
    "texinfo",
    "roff",
    "t",
    "tr",
    "man",
    "me",
    "ms",
    "ustar",
    "src",
    "xsl",
    "rdf",
    "wsdl",
    "xpdl",
    "zip",
    "3gp",
    "3gpp",
    "3g2",
    "3gpp2",
    "aac",
    "adts",
    "loas",
    "ass",
    "au",
    "snd",
    "mp3",
    "mp2",
    "opus",
    "aif",
    "aifc",
    "aiff",
    "ra",
    "wav",
    "avif",
    "bmp",
    "gif",
    "ief",
    "jpg",
    "jpe",
    "jpeg",
    "heic",
    "heif",
    "png",
    "svg",
    "tiff",
    "tif",
    "ico",
    "ras",
    "pnm",
    "pbm",
    "pgm",
    "ppm",
    "rgb",
    "xbm",
    "xpm",
    "xwd",
    "eml",
    "mht",
    "mhtml",
    "nws",
    "css",
    "csv",
    "html",
    "htm",
    "n3",
    "txt",
    "bat",
    "c",
    "h",
    "ksh",
    "pl",
    "srt",
    "rtx",
    "tsv",
    "vtt",
    "py",
    "etx",
    "sgm",
    "sgml",
    "vcf",
    "xml",
    "mp4",
    "mpeg",
    "m1v",
    "mpa",
    "mpe",
    "mpg",
    "mov",
    "qt",
    "webm",
    "avi",
    "movie",
]
